Try cross-build to arm also

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -16,22 +16,31 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Install Rust targets
-        run: rustup target add x86_64-pc-windows-gnu
+        run: |
+          rustup target add x86_64-pc-windows-gnu
+          rustup target add aarch64-unknown-linux-gnu
 
-      - name: Install Windows cross-compilation tools
-        run: sudo apt-get update && sudo apt-get install -y mingw-w64
+      - name: Install cross-compilation tools
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y mingw-w64 \
+          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
+          binutils-aarch64-linux-gnu \
+          libc6-dev-arm64-cross
 
-      - name: Build for Linux
-        run: cargo build --release --target x86_64-unknown-linux-gnu
-
-      - name: Build for Windows
-        run: cargo build --release --target x86_64-pc-windows-gnu
+      - name: Build Binaries
+        run: |
+          cargo build --release --target aarch64-unknown-linux-gnu
+          cargo build --release --target x86_64-unknown-linux-gnu
+          cargo build --release --target x86_64-pc-windows-gnu
 
       - name: Collect Binaries
         run: |
-          mkdir -p binaries
-          cp target/x86_64-unknown-linux-gnu/release/watermark-cli binaries/watermark-cli || echo "Linux binary not found"
-          cp target/x86_64-pc-windows-gnu/release/watermark-cli.exe binaries/watermark-cli.exe || echo "Windows binary not found"
+          mkdir -p binaries/aarch64
+          mkdir -p binaries/x86_64
+          cp target/aarch64-unknown-linux-gnu/release/watermark-cli binaries/aarch64/watermark-cli || echo "Linux aarch64 binary not found"
+          cp target/x86_64-unknown-linux-gnu/release/watermark-cli binaries/x86_64/watermark-cli || echo "Linux x86_64 binary not found"
+          cp target/x86_64-pc-windows-gnu/release/watermark-cli.exe binaries/x86_64/watermark-cli.exe || echo "Windows binary not found"
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
